### ISSUE TITLE
Filenames with spaces cause an error, even if quoted

### ISSUE THREAD

**Issue by rodneylives** [Fortyseven/extract-grid-overview#1]
The filename tried was:

.\extract-grid-overview.py ".\Pikmin Series Explained (in 9 minutes)-erNHF8ONhb4.webm" pikmin_grid.jpg -c 3 -r 3

**Comment by Fortyseven** [comment]
Are you on Windows or Linux/Mac?

**Comment by Fortyseven** [comment]
Nevermind, irrelevant. :grin:

**Comment by Fortyseven** [comment]
@rodneylives Sorry for the delay, last couple days have been chaos. Just pushed a fix for this. Let me know if it works for you! :)
